# Site information
title: Iker Pedrosa's blog
description: >- # this means to ignore newlines until next tag
  Software Engineer. Just another technology blog.
author: Iker Pedrosa
github_username:  ikerexxe
linkedin_url: https://linkedin.com/in/ikerpedrosa

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
